### ISSUE TITLE
HTTP endpoint subscription error

### ISSUE THREAD

**Issue by rodrigocarlospires** [p4tin/goaws#205]
Subscription to **http** endpoint from config file (goaws.yaml) don't work. So a **sns topic** configuration like that:

```
...
Topics:
    - Name: my_topic
      Subscriptions:
        - Protocol: http
          EndPoint: http://backend/my_listener
          TopicArn: arn:aws:sns:us-east-1:000000000000:my_topic
          FilterPolicy: '{"event": ["my_event"]}'
```
doesn't work!
From config file just subscription to SQS queues (*QueueName*) works! (on goaws container boot).

**TopicArn** like ListTopics response:
```
TopicArn: arn:aws:sns::000000000000:my_topic
```
also doesn't work :(

This way I need to subscribe manually (aws cli) to http endpoints every time the goaws is restarted.

Some solution to that?

Thanks!
