### ISSUE TITLE
SNS HTTP subscription FilterPolicy don't work

### ISSUE THREAD

**Issue by rodrigocarlospires** [p4tin/goaws#214]
HTTP FilterPolicy option seems not working! A config like that:

```
Topics:
    - Name: my_topic
      Subscriptions:
        - Protocol: http
          EndPoint: http://backend/my_listener_1
          TopicArn: arn:aws:sns:us-east-1:000000000000:my_topic
          FilterPolicy: '{"event": ["my_event_1"]}'
        - Protocol: http
          EndPoint: http://backend/my_listener_2
          TopicArn: arn:aws:sns:us-east-1:000000000000:my_topic
          FilterPolicy: '{"event": ["other_event", "another_event"]}'
```

With this config was expected the /my_listener_1 endpoint to receive notifications just from events published with "my_event_1" on message attributes. But all endpoints/subscriptions are receiving notifications for **any event published to SNS my_topic** (even for events published without MessageAttributes).

Can this be a bug? Or my config is wrong?

Thanks!
